#!/bin/bash
# Hyprland overrides: env, decoration, switcher binds, input, keybind allowlist
#
# See README.md in this directory for what this does and why.
# Runnable on its own, and called by ../apply.sh. $HERE is bound to overrides/
# (not this folder), so every path below reads exactly as it did when this
# lived in apply.sh.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib.sh"
HERE="$OVERRIDES"

# Each block is appended at the END of its file, which is what makes it win on
# load order — see the notes in the snippets themselves.
sync_fenced ~/.config/hypr/hyprland.lua  "$HERE/hypr/hyprland-env.lua"
sync_fenced ~/.config/hypr/looknfeel.lua "$HERE/hypr/looknfeel-decoration.lua"
sync_fenced ~/.config/hypr/bindings.lua  "$HERE/hypr/window-switcher-bindings.lua"
sync_fenced ~/.config/hypr/input.lua     "$HERE/hypr/input-tuning.lua"

# See README.md (1)
CURRENT="$HERE/hypr/keybind-current.conf"
ALLOWLIST="$HERE/hypr/keybind-allowlist.conf"

say "keybind-current.conf: rescanning every bind currently in effect"
tmp=$(mktemp)
lua "$HERE/hypr/keybind-scan.lua" dump >"$tmp"
if [[ ! -s $tmp ]]; then
  rm -f "$tmp"
  printf 'error: keybind scan produced nothing — leaving keybind files untouched\n' >&2
else
  {
    echo "# Every Hyprland keybind currently in effect, one per line as"
    echo "# \"keys<TAB>description\". Regenerated on every apply -- do not"
    echo "# hand-edit, edits here are discarded. Diff this against"
    echo "# keybind-allowlist.conf to see what's new/changed; edit that file"
    echo "# to actually prune something."
    echo "#"
    cat "$tmp"
  } >"$CURRENT"
  rm -f "$tmp"

  if [[ -e $ALLOWLIST ]]; then
# See README.md (2)
    skip "keybind-allowlist.conf already exists — not reseeding (edit it directly to prune,"
    skip "  or delete it and re-apply to reseed from this machine's own scan)"
  else
    say "seeding keybind-allowlist.conf from keybind-current.conf"
    {
      echo "# Your keybind whitelist. Delete a line to have the next apply run"
      echo "# unbind it. apply.sh never rewrites this file once it exists --"
      echo "# delete it yourself and re-apply to reseed from"
      echo "# keybind-current.conf."
      echo "#"
      grep -v '^#' "$CURRENT"
    } >"$ALLOWLIST"
  fi
fi

if [[ -e $ALLOWLIST ]]; then
  say "keybind-unbinds.lua: diffing keybind-current.conf against keybind-allowlist.conf"
  {
    echo "-- Generated by apply.sh from keybind-allowlist.conf. Do not hand-edit --"
    echo "-- edits here are overwritten on the next apply; edit"
    echo "-- keybind-allowlist.conf instead."
    lua "$HERE/hypr/keybind-scan.lua" unbinds "$ALLOWLIST"
  } >"$HERE/hypr/keybind-unbinds.lua"
  sync_fenced ~/.config/hypr/bindings.lua "$HERE/hypr/keybind-unbinds.lua" keybinds
fi

# See README.md (3)
sync_fenced ~/.config/hypr/bindings.lua "$HERE/hypr/macos-shortcuts.lua" macos-shortcuts

# See README.md (4)
sync_fenced ~/.config/hypr/bindings.lua "$HERE/hypr/window-management-mod.lua" window-management-mod

# Bibata is referenced by hyprland-env.lua and the gsettings below. No sudo
# here, so warn rather than install.
if [[ ! -d /usr/share/icons/Bibata-Modern-Ice && ! -d ~/.local/share/icons/Bibata-Modern-Ice ]]; then
  skip "cursor theme Bibata-Modern-Ice not found — install it with: yay -S bibata-cursor-theme-bin"
  skip "  (AUR, so pacman -S will not find it; the cursor setting below is applied regardless)"
fi
say "gsettings: cursor theme -> Bibata-Modern-Ice @ 22"
gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
gsettings set org.gnome.desktop.interface cursor-size 22

