#!/usr/bin/env python3
"""Rewrite yazi's icon table onto the terminal's ANSI palette.

yazi ships ~725 icon rules, each `{ name = "...", text = "<glyph>", fg = "#hex" }`,
and the fg values are fixed hex -- so while everything else in yazi/theme.toml
follows `omarchy theme set`, the icon glyphs stayed a fixed material-design
palette. Measured before this existed: a directory row emitted
`38;2;3;169;244` for the glyph and `34m` (our ANSI blue) for the name.

There is no "strip the colour" switch: an [icon] rule carries its own glyph, so
overriding a colour means restating the rule, and restating *some* rules blanks
the glyphs of the ones you left out. Hence this -- it reproduces yazi's whole
table, verbatim apart from the fg values, which are bucketed by HUE onto ANSI
colour names. Names, glyphs, ordering and yazi's own comments are preserved, so
the diff against the preset is only ever the colours.

The table is read out of the yazi BINARY (both presets are embedded as TOML),
not vendored from upstream, so re-running after a yazi upgrade picks up new
icons. Re-run it then -- like colors.svg and unlock.svg, it does not stay in
sync on its own:

    ./overrides/yazi/generate-icons.py

It rewrites the fenced block at the end of overrides/yazi/theme.toml in place.
"""
import colorsys
import io
import os
import re
import sys

BINARY = "/usr/bin/yazi"
HERE = os.path.dirname(os.path.abspath(__file__))
THEME = os.path.join(HERE, "theme.toml")
OPEN = "# >>> generated icon table >>>"
CLOSE = "# <<< generated icon table <<<"


def ansi_for(hex6):
    """Bucket a hex colour onto an ANSI colour NAME by hue.

    Saturation decides neutral-vs-hued first: a grey icon has no hue to
    preserve, and `reset` (the terminal's own foreground) tracks the theme
    better than picking a grey out of the palette. Value then picks the base
    or bright slot within a hue, which roughly preserves yazi's own light/dark
    pairs -- ANSI has 8 hues where yazi used 219 colours, so the bright row is
    what keeps some of that separation.

    Orange and pink have no ANSI slot and fold into yellow and magenta.
    """
    r, g, b = (int(hex6[i:i + 2], 16) / 255 for i in (1, 3, 5))
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    if s < 0.12:
        return "darkgray" if v < 0.35 else "reset"
    h *= 360
    if h < 16 or h >= 345:
        base = "red"
    elif h < 45:
        base = "yellow"      # orange: no ANSI slot of its own
    elif h < 70:
        base = "yellow"
    elif h < 160:
        base = "green"
    elif h < 200:
        base = "cyan"
    elif h < 260:
        base = "blue"
    elif h < 320:
        base = "magenta"
    else:
        base = "magenta"     # pink
    return "light" + base if (v >= 0.70 and s >= 0.45) else base


def extract_sections(blob):
    """Both preset themes embed an [icon] section; return them in file order."""
    marker = "# : }}}"
    out = []
    for m in re.finditer(r"\[icon\]\nglobs = \[\]", blob):
        out.append(blob[m.start():blob.index(marker, m.start())])
    return out


def main():
    if not os.path.exists(BINARY):
        sys.exit("yazi not found at %s" % BINARY)
    blob = io.open(BINARY, "rb").read().decode("utf-8", "ignore")
    secs = extract_sections(blob)
    if len(secs) < 2:
        sys.exit("expected two embedded [icon] sections, found %d — yazi's "
                 "preset layout changed; re-check this script" % len(secs))

    # Take the DARK preset (the brighter of the two). Its hues are the more
    # saturated set, and the two agree on hue bucket for 720 of 725 rules, so
    # one ANSI mapping serves both -- which it must, since a single theme.toml
    # is read for either appearance.
    def mean_value(sec):
        vals = []
        for c in re.findall(r'fg = "(#[0-9a-fA-F]{6})"', sec):
            r, g, b = (int(c[i:i + 2], 16) / 255 for i in (1, 3, 5))
            vals.append(colorsys.rgb_to_hsv(r, g, b)[2])
        return sum(vals) / len(vals) if vals else 0.0

    sec = max(secs, key=mean_value)
    n = [0]

    def sub(m):
        n[0] += 1
        return 'fg = "%s"' % ansi_for(m.group(1))

    sec = re.sub(r'fg = "(#[0-9a-fA-F]{6})"', sub, sec)
    if re.search(r'#[0-9a-fA-F]{6}', sec):
        sys.exit("a hex colour survived the rewrite — bailing rather than "
                 "shipping a half-converted table")
    sec = sec.rstrip() + "\n"

    theme = io.open(THEME, encoding="utf-8").read()
    block = "%s\n# %d rules, regenerated by generate-icons.py — do not hand-edit.\n%s%s\n" % (
        OPEN, n[0], sec, CLOSE)
    if OPEN in theme:
        # A LAMBDA, not the string itself. re.sub expands backslash escapes in
        # its replacement -- \1, \g<...>, \n -- so passing the generated block
        # directly makes any backslash yazi ships in an icon name or glyph
        # either raise `re.error: bad escape` or silently become something
        # else. The current table happens to have none, which is exactly what
        # would make the next upgrade's failure hard to place.
        theme = re.sub(re.escape(OPEN) + r".*?" + re.escape(CLOSE) + r"\n?",
                       lambda _m: block, theme, flags=re.S)
    else:
        theme = theme.rstrip() + "\n\n" + block
    io.open(THEME, "w", encoding="utf-8").write(theme)
    print("rewrote %d icon colours into %s" % (n[0], THEME))


if __name__ == "__main__":
    main()
