#!/usr/bin/env python3
"""Take Chromium's UI off the tinted palette Omarchy's theme colour generates.

Omarchy hands every theme's seed to Chromium as the `BrowserThemeColor` managed
policy, and Chromium runs that seed through Material's tonal-spot scheme, which
FORCES chroma onto the generated palette. A zero-chroma seed has no hue of its
own to force, so it lands on the scheme's default hue and the whole browser
comes out faintly cyan. Both of our themes ship a pure grey (`#ECECEC` light,
`#1E1E1E` dark), so both hit it exactly -- `chromium.theme` is not the fix it
was once documented as, it is an instance of the bug.

Two profile preferences are needed, because they cover different halves of the
UI and neither is enough alone. Both measured on Chromium 152 in a throwaway
profile under the live policy:

  extensions.theme.system_theme = 1   the system (GTK) theme.
      Takes the FRAME and the MENUS out of the autogenerated palette:
      menu background rgb(248,253,254) -> rgb(255,255,255), separators
      rgb(200,246,254) -> rgb(242,242,242).

  browser.theme.is_grayscale2 = true  the grayscale theme.
      Takes the ACCENT with it, which the GTK theme does not: with the system
      theme alone the omnibox focus ring is still a dark teal, and it goes back
      to Chromium's own blue with this set. This is the key that survives the
      policy -- `browser.theme.user_color2` does not (measured: a blue one
      changed nothing at all).

The seed cannot be fixed from the other end, and the obvious attempt makes
things worse: pushing the theme's own accent (`#007AFF`) through the policy
paints the tab strip dark blue (active tab rgb(24,92,162)), because a seed with
real chroma themes the frame as designed. The grey seed plus these two keys is
the combination that leaves the browser neutral.

Both are profile state with no flag and no policy behind them, so they are
written here the same way page zoom is, with the same "quit Chromium first"
rule -- Chromium rewrites Preferences from memory when it exits, so a write
made while it is running is silently discarded.

Usage:  neutral-theme.py             system theme + grayscale
        neutral-theme.py --print     the current pair, or nothing if unset
        neutral-theme.py --reset     delete both keys (Chromium's own applies)
        neutral-theme.py st=1,gs=1   restore an exact pair (what --print emits;
                                     an empty half deletes that key)
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import chromium_prefs  # noqa: E402  (path has to be set first)

from chromium_prefs import LABEL, profiles, running  # noqa: E402

# ui::SystemTheme's value for the desktop's own theme. Measured rather than read
# out of a header: 1 is what produced the neutral GTK frame and menus above.
GTK = 1

# (section, key) for each half, in the order --print emits them.
KEYS = (
    ("st", ("extensions", "theme"), "system_theme"),
    ("gs", ("browser", "theme"), "is_grayscale2"),
)

OURS = {"st": GTK, "gs": True}


def _node(data, path, create):
    node = data
    for part in path:
        if part not in node:
            if not create:
                return None
            node[part] = {}
        node = node[part]
        if not isinstance(node, dict):
            return None
    return node


def apply(path, wanted):
    """wanted maps short name -> value, or None for "delete this key"."""
    name = os.path.basename(path)

    data = chromium_prefs.read(path)
    if data is None:
        return False

    changed = []
    for short, section, key in KEYS:
        if short not in wanted:
            continue
        value = wanted[short]
        node = _node(data, section, create=value is not None)
        current = None if node is None else node.get(key)
        if value is None:
            # Reset DELETES rather than writing a value, so the setting goes
            # back to whatever Chromium's own default is instead of this script
            # asserting one -- same reasoning as default-zoom.py.
            if node is None or current is None:
                continue
            node.pop(key, None)
            changed.append(f"{key} cleared")
        else:
            if current == value:
                continue
            node[key] = value
            changed.append(f"{key}={str(value).lower()}")

    if not changed:
        print(f"  - {name}: already neutral")
        return False

    chromium_prefs.write(path, data)
    print(f"  • {name}: {', '.join(changed)}")
    return True


def read_pair():
    """The first profile that sets either key, as `st=…,gs=…`, or ''.

    apply.sh captures this to record what the machine had before its first
    apply, the same way it records the pre-existing zoom, font and theme, and
    revert.sh hands the same string straight back to this script.
    """
    for path in profiles():
        data = chromium_prefs.read(path)
        if not data:
            continue
        parts = []
        for short, section, key in KEYS:
            node = _node(data, section, create=False)
            value = None if node is None else node.get(key)
            parts.append(f"{short}={'' if value is None else int(value)}")
        if any(p.split("=", 1)[1] for p in parts):
            return ",".join(parts)
    return ""


def parse(raw):
    """`st=1,gs=` -> {"st": 1, "gs": None}. Unknown names are a hard error."""
    wanted = {}
    names = {short for short, _, _ in KEYS}
    for chunk in raw.split(","):
        short, _, value = chunk.partition("=")
        short = short.strip()
        if short not in names:
            sys.exit(f"{chunk!r} is not one of {', '.join(sorted(names))}")
        value = value.strip()
        if value == "":
            wanted[short] = None
        elif short == "gs":
            wanted[short] = value not in ("0", "false", "False")
        else:
            try:
                wanted[short] = int(value)
            except ValueError:
                sys.exit(f"{value!r} is not a number")
    return wanted


def main():
    raw = sys.argv[1].strip() if len(sys.argv) > 1 and sys.argv[1].strip() else ""

    if raw == "--print":
        out = read_pair()
        if out:
            print(out)
        return 0

    if raw == "--reset":
        wanted = {short: None for short, _, _ in KEYS}
    elif raw:
        wanted = parse(raw)
    else:
        wanted = dict(OURS)

    if running():
        print(f"  - {LABEL} is running; it would overwrite Preferences on exit "
              "— quit it and re-run")
        return 0

    # A list, NOT a generator: any() short-circuits on the first True, which
    # over a genexp would leave every profile after the first one unwritten.
    changed = any([apply(p, wanted) for p in profiles()])
    if changed:
        print(f"    (applies to {LABEL} windows opened from now on)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
